### ISSUE TITLE
Missing images in 'My maths is wrong'

### ISSUE THREAD

**Issue by jakubfiala** [hughrawlinson/millenniumfal.com#1]
I particularly like the post `2013-11-17-my-maths-is-wrong` and I'd like to see the data, but it seems that the images you're linking to in the MD aren't in the repo.

**Comment by hughrawlinson** [comment]
Ah yes, I knew something would be lost in the migration from Ghost to Jekyll. Thanks for letting me know, I'll see if I can sort it :)

**Comment by hughrawlinson** [comment]
Sorted. [Here](http://www.millenniumfal.com/2013/11/17/my-maths-is-wrong.html)'s your favourite post returned to it's full glory :shipit: :sparkles:

**Comment by jakubfiala** [comment]
awesome :+1:
